### ISSUE TITLE
Seg fault on linux

### ISSUE THREAD

**Issue by spmn** [Zeex/sampgdk#169]
Right at plugin loading:

```
Program received signal SIGSEGV, Segmentation fault.
0xf7bd14e1 in _sampgdk_callback_compare_name (elem=0x81d3900, key=0xf7be2ddd) at ./lib/sampgdk/sampgdk.c:2405
2405	  return strcmp((const char *)key,
(gdb) bt
#0  0xf7bd14e1 in _sampgdk_callback_compare_name (elem=0x81d3900, 
    key=0xf7be2ddd) at ./lib/sampgdk/sampgdk.c:2405
#1  bsearch (__compar=<optimized out>, __size=<optimized out>, 
    __nmemb=4294967295, __base=0x81d3908, __key=0xf7be2ddd)
    at /usr/include/bits/stdlib-bsearch.h:33
#2  _sampgdk_callback_find (name=0xf7be2ddd "OnPublicCall2")
    at ./lib/sampgdk/sampgdk.c:2417
#3  _sampgdk_callback_register_special (name=0xf7be2ddd "OnPublicCall2")
    at ./lib/sampgdk/sampgdk.c:2431
#4  sampgdk_callback_init () at ./lib/sampgdk/sampgdk.c:2469
#5  0xf7be133d in sampgdk_module_init () at ./lib/sampgdk/sampgdk.c:284
#6  0xf7be1492 in _sampgdk_init (plugin_data=0x81d3328)
    at ./lib/sampgdk/sampgdk.c:3244
#7  _sampgdk_init_plugin (plugin_data=0x81d3328, plugin=<optimized out>)
    at ./lib/sampgdk/sampgdk.c:3260
#8  sampgdk_Load (ppData=0x81d3328, hidden=0) at ./lib/sampgdk/sampgdk.c:3297
#9  0xf7bcc2a0 in Load (ppData=0x81d3328) at ./src/main.cpp:44
#10 0x080d2742 in ?? ()
#11 0x080d2afa in ?? ()
#12 0x080aa0d0 in ?? ()
#13 0xf7c1979e in __libc_start_main () from /lib32/libc.so.6
```

I'm using sampgdk 4.5.0 amalgamation (latest version atm). Previous release works like a charm.

Probably related to #167 

// Later edit: Just tested on Windows and .. it seems to work.

**Comment by WopsS** [comment]
I think you had the same problem as mem when **_sampgdk_callback_num_callbacks** return **-1**, Check 3a3361698c19e5c8fb91ec16d3098ca93d7deae9 for a temporary fix. This is a problem when you compile C code as C++.

**Comment by spmn** [comment]
https://github.com/Zeex/sampgdk/commit/f4eec317448a35153bb74a9d6ad12d679c3b62ac did the trick.

Shame on me because I saw your PR, but the name you choose for it was misleading since the title says that your fix applies only when sampgdk is being compiled as C++ code, but I explicitely compiled sampgdk as C on Linux, so I completely ignored it.
